{
  'targets': [{
    'target_name': 'audioMixer',
    'sources': [
      'addon.cc',
      'AudioMixerWrapper.cc',
      'AudioMixer.cpp',
      'AcmDecoder.cpp',
      'FfDecoder.cpp',
      'AcmEncoder.cpp',
      'PcmEncoder.cpp',
      'FfEncoder.cpp',
      'AcmmFrameMixer.cpp',
      'AcmmBroadcastGroup.cpp',
      'AcmmGroup.cpp',
      'AcmmInput.cpp',
      'AcmmOutput.cpp',
      'AudioTime.cpp',
      '../../addons/common/NodeEventRegistry.cc',
      '../../../core/owt_base/MediaFramePipeline.cpp',
      '../../../core/owt_base/AudioUtilities.cpp',
      '../../../core/owt_base/WinPort.cpp',
    ],
    'defines': [
            'NOMINMAX',
            '_WIN32_WINNT=0x0A00',
            'WEBRTC_WIN',
          ],
    "msvs_settings": {
          "VCCLCompilerTool": {
            'RuntimeTypeInfo': 'true',
            "ExceptionHandling": "1",
            'AdditionalOptions': ['/GR'], 
          },
      },
    'cflags_cc': [
        '-Wall',
        '-O$(OPTIMIZATION_LEVEL)',
        '-g',
        '-std=c++11',
        '-DWEBRTC_POSIX',
    ],
    'cflags_cc!': [
        '-fno-exceptions',
    ],
    'include_dirs': [ '$(CORE_HOME)/common',
                      '$(CORE_HOME)/owt_base',
                      '$(CORE_HOME)/../../third_party/webrtc/src',
                      '$(CORE_HOME)/../../build/libdeps/build/include',
                      '$(CORE_HOME)/../../third_party/boost_1.72.0/include',
                      '$(CORE_HOME)/../../third_party/log4cxx/src/apache-log4cxx-0.10.0/src/main/include',
    ],
    'library_dirs': [
      '$(CORE_HOME)/../../build/libdeps/build/lib',
      '$(CORE_HOME)/../../third_party/boost_1.72.0/lib/windows/x64/release',
      '$(CORE_HOME)/../../third_party/lib',
    ],    
    'libraries': [
      '-lboost_thread-vc140-mt.lib',
      '-llog4cxx',
      '-lwebrtc',
      '-lavutil',
      '-lavcodec',
      '-lavformat',
      '-lswresample',
      '-lWinmm.lib',
    ],
  }]
}
