{
  'targets': [{
    'target_name': 'webrtc',
    'sources': [
      'addon.cc',
      'AudioFrameConstructorWrapper.cc',
      'AudioFramePacketizerWrapper.cc',
      'VideoFrameConstructorWrapper.cc',
      'VideoFramePacketizerWrapper.cc',
      'WebRtcConnection.cc',
      "MediaStream.cc",
      'conn_handler/WoogeenHandler.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/DtlsTransport.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/IceConnection.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/LibNiceConnection.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/SdpInfo.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/SrtpChannel.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/Stats.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/StringUtil.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/WebRtcConnection.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/MediaStream.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/lib/LibNiceInterfaceImpl.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/thread/IOThreadPool.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/thread/IOWorker.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/thread/Scheduler.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/thread/ThreadPool.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/thread/Worker.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/rtp/PacketBufferService.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/rtp/RtcpForwarder.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/rtp/RtcpProcessorHandler.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/rtp/RtpUtils.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/rtp/QualityManager.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/rtp/RtpExtensionProcessor.cpp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/rtp/BandwidthEstimationHandler.cpp',
      'D:/workspace/owt-server/third_party/licode/erizo/src/erizo/dtls/bf_dwrap.c',
      'D:/workspace/owt-server/third_party/licode/erizo/src/erizo/dtls/DtlsClient.cpp',
      'D:/workspace/owt-server/third_party/licode/erizo/src/erizo/dtls/DtlsSocket.cpp',
      'D:/workspace/owt-server/third_party/licode/erizo/src/erizo/pipeline/Pipeline.cpp',
      'D:/workspace/owt-server/third_party/licode/erizo/src/erizo/stats/StatNode.cpp',
      '../../addons/common/NodeEventRegistry.cc',
      '../../../core/owt_base/AudioFrameConstructor.cpp',
      '../../../core/owt_base/AudioFramePacketizer.cpp',
      '../../../core/owt_base/AudioUtilities.cpp',
      '../../../core/owt_base/MediaFramePipeline.cpp',
      '../../../core/owt_base/VideoFrameConstructor.cpp',
      '../../../core/owt_base/VideoFramePacketizer.cpp',
      '../../../core/owt_base/SsrcGenerator.cc',
      '../../../core/rtc_adapter/VieReceiver.cc',
      '../../../core/rtc_adapter/VieRemb.cc' #20150508
    ],
    'defines': [
            'NOMINMAX',
            '_WIN32_WINNT=0x0A00',
            'WIN32_LEAN_AND_MEAN',
            'WEBRTC_WIN',
            'NO_REG_RPC=1', 'HAVE_VFPRINTF=1', 'RETSIGTYPE=void', 'NEW_STDIO', 'HAVE_STRDUP=1', 'HAVE_STRLCPY=1', 'HAVE_LIBM=1', 'HAVE_SYS_TIME_H=1', 'TIME_WITH_SYS_TIME_H=1','V8_IMMINENT_DEPRECATION_WARNINGS'
          ],
    "msvs_settings": {
          "VCCLCompilerTool": {
            'RuntimeTypeInfo': 'true',
            "ExceptionHandling": "1",
            'AdditionalOptions': ['/GR','/FI\"winsock2.h\"','/FI\"windows.h\"']
          },
      },
    'cflags_cc': ['-DWEBRTC_POSIX', '-DWEBRTC_LINUX', '-DLINUX', '-DNOLINUXIF', '-DNO_REG_RPC=1', '-DHAVE_VFPRINTF=1', '-DRETSIGTYPE=void', '-DNEW_STDIO', '-DHAVE_STRDUP=1', '-DHAVE_STRLCPY=1', '-DHAVE_LIBM=1', '-DHAVE_SYS_TIME_H=1', '-DTIME_WITH_SYS_TIME_H=1'],
    'include_dirs': [
      "<!(node -e \"require('nan')\")",
      'conn_handler',
      'D:/workspace/owt-server/source/core/../../third_party',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/lib',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/dtls',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/pipeline',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/rtp',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/thread',
      'D:/workspace/owt-server/source/core/../../third_party/licode/erizo/src/erizo/stats',
      '../../../core/common',
      '../../../core/owt_base',
      '../../../core/rtc_adapter',
      '../../../../third_party/webrtc/src',
      '../../../../build/libdeps/build/include',
      '../../../../build/libdeps/libnice-0.1.4/glib/include/glib-2.0',
      '../../../../build/libdeps/libnice-0.1.4/glib/lib/glib-2.0/include',
      'D:/workspace/vcpkg/installed/x64-windows-static/include',
      'D:/workspace/log4cxx/src/apache-log4cxx-0.10.0/src/main/include',
      # '<!@(pkg-config glib-2.0 --cflags-only-I | sed s/-I//g)',
    ],
    'library_dirs': [
      'D:/workspace/owt-server/source/core/../../build/libdeps/build/lib',
      'D:/workspace/log4cxx/src/apache-log4cxx-0.10.0/projects/x64/Release',
      'D:/workspace/vcpkg/installed/x64-windows-static/lib',
    ],
    'libraries': [
      # '-LD:/workspace/owt-server/source/core/../../build/libdeps/build/lib',
      '-lsrtp2',
      '-llibssl',
      # '-ldl',
      '-llibcrypto',
      '-llog4cxx',
      '-lD:/workspace/vcpkg/installed/x64-windows-static/lib/boost_thread-vc140-mt.lib',
      '-lD:/workspace/vcpkg/installed/x64-windows-static/lib/boost_system-vc140-mt.lib',
      '-llibnice',
      '-lD:/workspace/owt-server/source/core/../../build/libdeps/libnice-0.1.4/glib/lib/glib-2.0.lib',
      '-lD:/workspace/owt-server/source/core/../../build/libdeps/libnice-0.1.4/glib/lib/gobject-2.0.lib',
      '-lD:/workspace/owt-server/source/core/../../third_party/webrtc/webrtc',
      '-lD:/workspace/owt-server/source/core/../../build/libdeps/build/bin/avutil',
      '-lD:/workspace/owt-server/source/core/../../build/libdeps/build/bin/avcodec',
      '-lD:/workspace/owt-server/source/core/../../build/libdeps/build/bin/avformat',
      '-lD:/workspace/owt-server/source/core/../../build/libdeps/build/bin/swresample',
      '-lD:/workspace/owt-server/source/core/../../third_party/openh264/openh264',
      '-lWinmm.lib',
      '-lCrypt32.lib',
    ],
    'conditions': [
      [ 'OS=="mac"', {
        'xcode_settings': {
          'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',        # -fno-exceptions
          'MACOSX_DEPLOYMENT_TARGET':  '10.7',       # from MAC OS 10.7
          'OTHER_CFLAGS': ['-g -O$(OPTIMIZATION_LEVEL) -stdlib=libc++']
        },
      }, { # OS!="mac"
          'cflags!' : ['-fno-exceptions'],
          'cflags' : ['-D__STDC_CONSTANT_MACROS'],
          'cflags_cc' : ['-Wall', '-O3', '-g' , '-std=c++11', '-fexceptions'],
          'cflags_cc!' : ['-fno-exceptions'],
          'cflags_cc!' : ['-fno-rtti']
      }],
    ]
  }]
}
